name: Merge on master
on:
  push:
    branches:
      - master

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ftrip-io/github-ci/semantic-release@cddb7cfea7f0db23dad42020ba7c4e1a6d456226
        id: semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ftrip-io/github-ci/build-and-push-to-dockerhub@ef2fd6ac85fe9e0ae63e5979a82a35bd5075bc33
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          context: "ftrip.io.user-service"
          tags: ftripio/user-service:latest, ftripio/user-service:${{ steps.semantic-release.outputs.next-version }}
