name: PR to develop/master
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/ftrip.io.user-service/.nuget/packages
      DOTNET_INSTALL_DIR: ./.dotnet
      CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v3

      - name: Cache .NET 3.1
        id: cache-dotnet
        uses: actions/cache@v3
        with:
          path: ${{ env.DOTNET_INSTALL_DIR }}
          key: ${{ runner.os }}-dotnet-3.1

      - name: Setup .NET 3.1
        if: steps.cache-dotnet.outputs.cache-hit != 'true'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1

      - name: Cache .NET ReportGenerator
        id: cache-dotnet-reportgenerator
        uses: actions/cache@v3
        with:
          path: ./.tools/reportgenerator
          key: ${{ runner.os }}-dotnet-reportgenerator

      - name: Install .NET ReportGenerator
        if: steps.cache-dotnet-reportgenerator.outputs.cache-hit != 'true'
        run: |
          dotnet tool install dotnet-reportgenerator-globaltool --tool-path ./.tools/reportgenerator

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          dotnet restore /p:Configuration=${{ env.CONFIGURATION }} ftrip.io.user-service/ftrip.io.user-service.sln

      - name: Build, Analyze and Generate Code Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          shopt -s expand_aliases
          alias dotnet3="${{ env.DOTNET_INSTALL_DIR }}/dotnet"
          alias reportgenerator="./.tools/reportgenerator/reportgenerator"
          alias sonarscanner="./.sonar/scanner/dotnet-sonarscanner"

          sonarscanner begin /k:"ftrip-io_user-service" /o:"ftrip-io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths=TestResults/*.trx /d:sonar.cs.opencover.reportsPaths=TestResults/*/coverage.opencover.xml /d:sonar.coverage.exclusions="**Test*.cs"

          dotnet3 build ftrip.io.user-service/ftrip.io.user-service.sln \
            --no-restore \
            -c ${{ env.CONFIGURATION }}
          dotnet3 publish ftrip.io.user-service/ftrip.io.user-service/ftrip.io.user-service.csproj \
            --no-build \
            --no-restore \
            -c ${{ env.CONFIGURATION }}
          dotnet3 test ftrip.io.user-service/ftrip.io.user-service.unit-tests/ftrip.io.user-service.unit-tests.csproj \
            --no-build \
            --no-restore \
            -c ${{ env.CONFIGURATION }} \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults/ \
            --logger "trx;LogFileName=unittests.trx" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          reportgenerator \
           -reports:TestResults/**/coverage.opencover.xml \
           -targetdir:code-coverage \
           -reporttypes:Html

          sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          files: |
            TestResults/**/*.trx

      - name: Upload Code Coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: Code Coverage
          path: code-coverage
